---
- name: Create Logstash configuration files.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 01-beats-input.conf
    - 30-elasticsearch-output.conf
  notify: restart logstash

- name: Create Logstash filters.
  copy:
    src: "{{ item }}"
    dest: "/etc/logstash/conf.d/"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - "{{ logstash_filters_fileglob | default('') }}"
  #with_items:
  #  - 10-syslog.conf
  #  - 11-nginx.conf
  #  - 12-apache.conf
  #  - 14-solr.conf
  #  - 15-drupal.conf
  notify: restart logstash

- name: Create Logstash configuration file for local syslog.
  template:
    src: 02-local-syslog-input.conf.j2
    dest: /etc/logstash/conf.d/02-local-syslog-input.conf
    owner: root
    group: root
    mode: 0644
  when: logstash_monitor_local_syslog
  notify: restart logstash

- name: Ensure configuration for local syslog is absent if disabled.
  file:
    path: /etc/logstash/conf.d/02-local-syslog-input.conf
    state: absent
  when: not logstash_monitor_local_syslog
  notify: restart logstash

- name: Create template directory.
  file:
    path: /etc/logstash/templates
    state: directory

- name: Create Elasticsearch template.
  copy:
    src: "{{ item }}"
    dest: "/etc/logstash/templates/"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - "{{ logstash_templates_fileglob }}"
  #with_items:
  #  - hel_base.json
  #  - apilogs_template.json
  #  - varnish_template
  notify: restart logstash
