---
logstash_version: '6.x'

logstash_listen_port_beats: 5044

logstash_elasticsearch_hosts:
  - http://localhost:9200

logstash_local_syslog_path: /var/log/syslog
logstash_monitor_local_syslog: true

logstash_dir: /usr/share/logstash

es_templates_dir: "files/es_templates/"
logstash_filters_fileglob: "files/filters/*.conf"

logstash_ssl_dir: /etc/pki/logstash
#openssl genrsa -des3 -out files/certs/myCA.key 2048
#openssl req -x509 -new -nodes -key files/certs/myCA.key -sha256 -days 1825 -out files/certs/myCA.pem
logstash_ssl_certificate_authorities: "{{ filebeat_ssl_certificate_authorities }}"
#openssl genrsa -out files/certs/filebeat.key 2048
#openssl req -new -key files/certs/filebeat.key -out files/certs/filebeat.csr
#openssl x509 -req -in files/certs/filebeat.csr -CA files/certs/myCA.pem -CAkey files/certs/myCA.key -CAcreateserial -out files/certs/filebeat.crt -days 1825 -sha256
logstash_ssl_certificate_file: "{{ filebeat_ssl_certificate_file }}"
logstash_ssl_key_file: "{{ filebeat_ssl_key_file }}"
logstash_enabled_on_boot: true

logstash_install_plugins:
  - logstash-input-beats
